package ports

import "time"

// Clock supplies the current instant.
//
// This port is consumed by internal/brain, not by internal/core: the brain reads
// the clock once at the start of an operation and passes the resulting time.Time
// down as a plain argument, so a single decision always sees a single instant.
// Lint rejects both time.Now and an import of this package from within the core.
//
// Almost every behavior in Nooma is a function of time — decay, trigger firing,
// quiet hours, staleness gates, recurrence, cooldowns — so a real clock reached
// from inside the core would make each of them testable only by waiting, and would
// make the M2 demo ("a vault with simulated weeks of data") impossible.
//
// See docs/06-harness.md §2.
type Clock interface {
	Now() time.Time
}

// IDGen supplies unique identifiers.
//
// Identifiers are UUID v4 generated by the application (docs/03-data-model.md).
// Like Clock, it is consumed by internal/brain; the core receives generated ids as
// arguments so its output stays deterministic under test.
type IDGen interface {
	New() string
}
