package ports

import (
	"context"
	"time"

	"github.com/rengo/nooma/internal/core/relation"
)

// Relation is one relations row (migration 0001:30-40, docs/03-data-model.md)
// — design D8.
//
// Every field mirrors a column 1:1, following ports.Decision's own pattern:
// the caller assembles the full row, this port persists it, and no field is
// derived by the repository. ID is generated by internal/brain's ports.IDGen
// before Upsert is ever called (the same convention captureRunner already
// uses for units and decisions) — Upsert's own conflict target is the
// UNIQUE(from_unit_id, to_unit_id, type) constraint, not the primary key, so
// ID is what a second Upsert over the same triple must NOT overwrite (I07):
// the row that already exists keeps the id it was given the first time.
type Relation struct {
	ID         string
	FromUnitID string
	ToUnitID   string
	Type       string
	Strength   float64
	Confidence float64
	CreatedBy  string
	CreatedAt  time.Time
}

// RelationRepo is the repository port over relations — design D8, spec R5.3.
//
// Three methods, and each has a real caller (design D8's own rule for adding
// a port method): Upsert is the judge's persist step (PR 11c), ByUnit is
// Phase C's read-only units route showing a unit's related units, and
// ThresholdsFor is what feeds relation.Resolve — the two are meant to be
// called together, never ThresholdsFor alone with nothing to resolve.
//
// No Delete*-prefixed method — keeps
// test/conformance/i03_units_never_deleted_test.go's strengthened prefix set
// ({Delete, Remove, Purge, Drop, Destroy}) satisfied for every ports
// interface, not only ports.UnitRepo.
type RelationRepo interface {
	// Upsert writes r, updating strength and confidence in place when a row
	// already exists for r's (FromUnitID, ToUnitID, Type) triple — I07: a
	// second Upsert over the same triple must never violate
	// relations.UNIQUE(from_unit_id, to_unit_id, type) (confirmed present,
	// migration 0001:39) and must never produce a second row.
	//
	// Only Strength and Confidence change on an existing row. ID, CreatedBy
	// and CreatedAt are the identity and provenance of the FIRST judgment
	// over a pair — a later Upsert revising the confidence must not also
	// rewrite when the relation was first noticed or who noticed it.
	Upsert(ctx context.Context, r Relation) error

	// ByUnit returns every relation where unitID is either endpoint —
	// FromUnitID or ToUnitID — ordered by CreatedAt then ID for a
	// deterministic read. Phase C's units route renders "what this unit
	// relates to" as one list; a unit is as often the target of a relation
	// (e.g. a "duplicate" judgment naming an existing unit, design D7) as its
	// origin, and a route that only checked FromUnitID would silently drop
	// half of what a reader would call "this unit's relations".
	ByUnit(ctx context.Context, unitID string) ([]Relation, error)

	// ThresholdsFor returns relType's persist/surface thresholds, or (nil,
	// nil) when relation_thresholds holds no row for relType — design D8,
	// R5.6: relation type is open text, so no seed row could ever be
	// exhaustive, and (nil, nil) is exactly the input relation.Resolve
	// expects for "this type has never been looked up before". The caller,
	// never core/relation, performs this lookup (R5.1's purity MUST).
	ThresholdsFor(ctx context.Context, relType string) (*relation.Thresholds, error)
}
