package ports

import (
	"context"
	"time"

	"github.com/rengo/nooma/internal/core/consolidation"
	"github.com/rengo/nooma/internal/core/relation"
)

// Relation is one relations row (migration 0001:30-40, docs/03-data-model.md)
// — design D8.
//
// Every field mirrors a column 1:1, following ports.Decision's own pattern:
// the caller assembles the full row, this port persists it, and no field is
// derived by the repository. ID is generated by internal/brain's ports.IDGen
// before Upsert is ever called (the same convention captureRunner already
// uses for units and decisions) — Upsert's own conflict target is the
// UNIQUE(from_unit_id, to_unit_id, type) constraint, not the primary key, so
// ID is what a second Upsert over the same triple must NOT overwrite (I07):
// the row that already exists keeps the id it was given the first time.
type Relation struct {
	ID         string
	FromUnitID string
	ToUnitID   string
	Type       string
	Strength   float64
	Confidence float64
	CreatedBy  string
	CreatedAt  time.Time
}

// RelationRepo is the repository port over relations — design D8, spec R5.3.
//
// Five methods, and each has a real caller (design D8's own rule for adding
// a port method): Upsert is the judge's persist step (PR 11c), ByUnit is
// Phase C's read-only units route showing a unit's related units,
// ThresholdsFor is what feeds relation.Resolve — the two are meant to be
// called together, never ThresholdsFor alone with nothing to resolve —
// Evidence is strengthen's co-use join (design §4.2), and ExistingPairs is
// connect's exclusion lookup (design §4.2).
//
// No Delete*-prefixed method — keeps
// test/conformance/i03_units_never_deleted_test.go's strengthened prefix set
// ({Delete, Remove, Purge, Drop, Destroy}) satisfied for every ports
// repository interface, not only ports.UnitRepo: m2c PR 3 widened that
// test's reflection sweep to cover UnitRepo, RelationRepo, SelfModelRepo,
// ConfigRepo and StateRepo together (design §4.6, spec R2.7); a later PR
// widened it again to the remaining two, SignalRepo and EmbeddingRepo, so
// the sweep now covers every ports repository interface that exists,
// closing the gap an earlier revision of this comment named but did not
// yet close.
type RelationRepo interface {
	// Upsert writes r, updating strength and confidence in place when a row
	// already exists for r's (FromUnitID, ToUnitID, Type) triple — I07: a
	// second Upsert over the same triple must never violate
	// relations.UNIQUE(from_unit_id, to_unit_id, type) (confirmed present,
	// migration 0001:39) and must never produce a second row.
	//
	// Only Strength and Confidence change on an existing row. ID, CreatedBy
	// and CreatedAt are the identity and provenance of the FIRST judgment
	// over a pair — a later Upsert revising the confidence must not also
	// rewrite when the relation was first noticed or who noticed it.
	Upsert(ctx context.Context, r Relation) error

	// ByUnit returns every relation where unitID is either endpoint —
	// FromUnitID or ToUnitID — ordered by CreatedAt then ID for a
	// deterministic read. Phase C's units route renders "what this unit
	// relates to" as one list; a unit is as often the target of a relation
	// (e.g. a "duplicate" judgment naming an existing unit, design D7) as its
	// origin, and a route that only checked FromUnitID would silently drop
	// half of what a reader would call "this unit's relations".
	ByUnit(ctx context.Context, unitID string) ([]Relation, error)

	// ThresholdsFor returns relType's persist/surface thresholds, or (nil,
	// nil) when relation_thresholds holds no row for relType — design D8,
	// R5.6: relation type is open text, so no seed row could ever be
	// exhaustive, and (nil, nil) is exactly the input relation.Resolve
	// expects for "this type has never been looked up before". The caller,
	// never core/relation, performs this lookup (R5.1's purity MUST).
	ThresholdsFor(ctx context.Context, relType string) (*relation.Thresholds, error)

	// Evidence returns every relation joined to both endpoints'
	// last_touched_at, in one read — strengthen's own input (design §4.2,
	// spec R3.5). The alternative — relations, then units, then a zip in
	// brain — is two round trips and a correctness hazard if a unit moves
	// between them; this port declares the join instead.
	//
	// Evidence takes no since parameter, unlike IncompleteOlderThan
	// (ports.UnitRepo): strengthen's own co-use predicate compares against
	// a runtime value with no constant to pin, so pushing that comparison
	// into SQL would create a second implementation of the predicate with
	// nothing to hold it honest (design §4.1's asymmetry note). This is an
	// unbounded read — strengthen must see every relation — named as a
	// risk (design §12 R4), not mitigated.
	Evidence(ctx context.Context) ([]consolidation.RelationEvidence, error)

	// ExistingPairs reports, for each of pairs, whether a relation already
	// exists between its two endpoints — connect's exclusion lookup
	// (design §4.2, spec R3.6). Every pair in the returned map is keyed by
	// consolidation.CanonicalPair, so a relation stored a->b matches a
	// lookup built from b->a's canonical form. A pair with no stored
	// relation is absent from the returned map — never a false-valued
	// entry — so a caller cannot mistake "never checked" for "checked and
	// absent" by inspecting the zero value.
	ExistingPairs(ctx context.Context, pairs []consolidation.Pair) (map[consolidation.Pair]bool, error)
}
