package ports

import (
	"context"
	"errors"
	"time"
)

// TimerStatus is timers.status's vocabulary (migration 0001:66) — see
// TriggerStatus for why it lives in internal/ports and how it is pinned.
type TimerStatus string

// The timers.status vocabulary, in migration 0001:66's own order.
const (
	TimerStatusPending   TimerStatus = "pending"
	TimerStatusFired     TimerStatus = "fired"
	TimerStatusCancelled TimerStatus = "cancelled"
)

// AllTimerStatuses returns a fresh slice holding the three TimerStatus
// members — see AllTriggerStatuses for why it is a function.
func AllTimerStatuses() []TimerStatus {
	return []TimerStatus{TimerStatusPending, TimerStatusFired, TimerStatusCancelled}
}

// Timer is TimerRepo's write shape.
//
// A timer is ephemeral and never becomes a unit (I04), so timers carries
// no unit_id and this struct names none. There is no InterruptLevel field
// either — timers has no such column, and inventing one here would be a
// field with nowhere to be written.
type Timer struct {
	// ID is the timer's own id, generated by the caller.
	ID string
	// FireAt is when the timer comes due. timers.fire_at is NOT NULL
	// (migration 0001:63): a timer with no instant is not a timer.
	FireAt time.Time
	// ActionText is what to say when it fires, or nil for a generic
	// nudge (migration 0001:65). nil and "" are different values: the
	// column's NULL carries the meaning.
	ActionText *string
	// CreatedAt arrives as data — no method on this port reads a clock.
	CreatedAt time.Time
}

// DueTimer is TimerRepo's read shape: what the due scan needs, and nothing
// else. rendered_text is absent because nothing has written it yet — the
// LLM rephrasing at fire time is m3d's.
type DueTimer struct {
	ID         string
	FireAt     time.Time
	ActionText *string
}

// TimerRepo is the repository port over timers. It mirrors TriggerRepo's
// shape and every reason behind it — one method per transition, no target
// status, no removal verb, no parameterized read, no clock.
type TimerRepo interface {
	// Create persists t. It returns ErrTimerExists if a timer with t.ID
	// already exists. The row is created pending.
	Create(ctx context.Context, t Timer) error

	// Due returns every pending timer whose fire_at is at or before at,
	// ordered by (fire_at, id). timers carries no index, so this is a
	// full scan — accepted for v1 and named rather than mitigated.
	Due(ctx context.Context, at time.Time) ([]DueTimer, error)

	// Fire moves id from pending to fired and writes surfaced_at = at in
	// one statement. A timer's firing is its delivery — there is no
	// separate rendering step for it to wait on — so surfaced_at is
	// written here and not left NULL as a trigger's is. rendered_text is
	// untouched, not defaulted: m3d's fire-time rephrasing writes it when
	// it has a caller.
	//
	// It returns ErrTimerStatusConflict if id is no longer pending, and
	// ErrTimerNotFound if no timer with id exists.
	Fire(ctx context.Context, id string, at time.Time) error

	// Cancel moves id from pending to cancelled — doc 02 §8's own
	// vocabulary for a timer too stale to deliver. timers carries no
	// cancelled_at column, so no timestamp is written and none is
	// invented.
	//
	// It returns the same two errors as Fire, for the same reasons.
	Cancel(ctx context.Context, id string) error
}

// Sentinel errors ports.TimerRepo implementations return.
var (
	// ErrTimerNotFound is returned by Fire and Cancel when no timer with
	// the given id exists.
	ErrTimerNotFound = errors.New("timer not found")

	// ErrTimerExists is returned by Create when a timer with t.ID already
	// exists.
	ErrTimerExists = errors.New("timer already exists")

	// ErrTimerStatusConflict is returned by Fire and Cancel when the
	// timer's current status is not pending.
	ErrTimerStatusConflict = errors.New("timer is not in the expected status")
)
