package main

import (
	"context"
	"crypto/rand"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/rengo/nooma/internal/brain"
	"github.com/rengo/nooma/internal/channels/telegram"
	"github.com/rengo/nooma/internal/config"
	"github.com/rengo/nooma/internal/ports"
	"github.com/rengo/nooma/internal/providers/anthropic"
	"github.com/rengo/nooma/internal/providers/ollama"
	"github.com/rengo/nooma/internal/providers/openai"
	"github.com/rengo/nooma/internal/scheduler"
	"github.com/rengo/nooma/internal/store/sqlite"
)

// systemClock is the production ports.Clock — the one place in this binary
// that calls time.Now (nooma-core: internal/core and internal/brain never
// do; docs/06-harness.md §2). It hands CaptureService.Capture's own single
// read (design D4) a real instant; nothing else in this command reads the
// clock.
type systemClock struct{}

func (systemClock) Now() time.Time { return time.Now() }

// uuidGen is the production ports.IDGen: a version-4 UUID
// (docs/03-data-model.md: "TEXT UUID v4 generated by the application"),
// built over crypto/rand rather than a new module dependency for sixteen
// random bytes and two bit-level fixups.
type uuidGen struct{}

func (uuidGen) New() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		// The OS's entropy source failing is not a condition this binary
		// can degrade under — every id it would generate from here on is
		// unusable, the same posture serve already takes toward a broken
		// environment elsewhere in this command.
		panic(fmt.Sprintf("uuidGen: reading random bytes: %v", err))
	}
	b[6] = (b[6] & 0x0f) | 0x40 // version 4
	b[8] = (b[8] & 0x3f) | 0x80 // variant 10
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

// buildProvider constructs the client cfg.Providers[name] describes. lookup
// resolves an api_key_env name to its value, the same injected-environment
// shape every other config-adjacent call in this command already takes.
//
// It returns the client as `any` on purpose: which port(s) the result
// satisfies is not this function's decision. Only ollama.Client implements
// both ports.LLMProvider and ports.EmbeddingProvider today — anthropic.Client
// and openai.Client implement just the first, until 17 gives openai.Client
// an Embed method — so resolveTaskProviders below asserts the port each
// task actually needs at its own call site, rather than this function
// promising one it cannot always keep.
func buildProvider(p config.Provider, lookup func(string) (string, bool)) (any, error) {
	switch p.Type {
	case "anthropic":
		apiKey, _ := lookup(p.APIKeyEnv)
		return anthropic.NewClient(p.Endpoint, apiKey, p.Model, http.DefaultClient), nil
	case "openai":
		apiKey, _ := lookup(p.APIKeyEnv)
		return openai.NewClient(p.Endpoint, apiKey, p.Model, http.DefaultClient), nil
	case "ollama":
		return ollama.NewClient(p.Endpoint, p.Model, http.DefaultClient), nil
	default:
		return nil, fmt.Errorf("provider type %q has no client this binary wires (whisper_cpp is audio-only)", p.Type)
	}
}

// resolveTaskProviders resolves every task tasksM1Consumes names (design
// D18a) against cfg.Tasks and cfg.Providers, asserting each one to the port
// it actually needs. It reads tasksM1Consumes itself, not a restated copy —
// TestResolveTaskProvidersReadsTheSharedListNotACopy (tasks_test.go) proves
// it by swapping the package var and observing this function's own
// resolution follow it.
//
// ok is false whenever ANY of the three is unresolved: an unbound task, a
// task bound to a provider name absent from cfg.Providers (unreachable once
// Validate has run, checked again here defensively), a provider type this
// binary has no client for, or a provider whose type does not implement the
// port that task needs — an anthropic- or openai-typed embedding binding,
// until 17 lands. This is deliberately all-or-nothing, not a per-task
// degradation: RecallService.ScoredFor dereferences its own embed field
// unconditionally (unlike Candidates, it has no nil guard on a missing
// vector), so handing NewCaptureService/NewRecallService a nil
// ports.EmbeddingProvider is not a degraded leg — it is a nil-interface
// panic on the first capture or recall. Falling back to the honest 503 the
// existing nil-Deps guards (13b, 13c) already answer with is what "safe
// defaults are structural" (CLAUDE.md non-negotiable #7) means applied to a
// half-configured provider set, the same posture it already takes toward
// the auth token.
func resolveTaskProviders(cfg *config.Config, lookup func(string) (string, bool)) (llm, judge ports.LLMProvider, embed ports.EmbeddingProvider, embedModel string, ok bool) {
	for _, task := range tasksM1Consumes {
		binding, bound := cfg.Tasks[task]
		if !bound {
			return nil, nil, nil, "", false
		}
		provider, present := cfg.Providers[binding.Provider]
		if !present {
			return nil, nil, nil, "", false
		}
		client, err := buildProvider(provider, lookup)
		if err != nil {
			return nil, nil, nil, "", false
		}

		switch task {
		case "capture_processing":
			p, isLLM := client.(ports.LLMProvider)
			if !isLLM {
				return nil, nil, nil, "", false
			}
			llm = p
		case "relation_evaluation":
			p, isLLM := client.(ports.LLMProvider)
			if !isLLM {
				return nil, nil, nil, "", false
			}
			judge = p
		case "embedding":
			p, isEmbed := client.(ports.EmbeddingProvider)
			if !isEmbed {
				return nil, nil, nil, "", false
			}
			embed = p
			embedModel = provider.Model
		}
	}
	return llm, judge, embed, embedModel, true
}

// wireBrain builds the real CaptureService/RecallService pair over db and
// cfg — design D10's own "config -> providers -> repos -> Index -> services"
// chain, resolved once at vault open (ADR-0012), not per request.
//
// It returns nil, nil (no error) whenever resolveTaskProviders could not
// resolve every task tasksM1Consumes names: that is not a startup failure,
// it is the same transitional state cmd/nooma/serve.go was already in
// before this PR, now reachable by a genuine configuration gap (a fresh
// vault with no providers bound yet) rather than only by "13d has not
// landed." The caller passes the result straight into
// httpapi.Handler(Deps{Capture, Recall}), whose existing nil guards (13b,
// 13c) answer it honestly over HTTP instead of this command refusing to
// serve at all.
// resolveConsolidateProviders resolves every task tasksConsolidateConsumes
// names into the two ports.LLMProvider/ports.EmbeddingProvider slots
// ConsolidateService needs. Unlike resolveTaskProviders' all-or-nothing
// bool (right for serve's own degrade-to-nil posture), this names the
// first task it cannot resolve — unbound, bound to an unconfigured
// provider name, an unbuildable provider type, or a provider that does
// not implement the port that task needs — because runConsolidate's own
// refusal (design §7.2) must tell the operator what to fix, not just that
// something failed.
//
// judge serves BOTH relation_evaluation's connect call and
// belief_derivation's derive call: consolidateRunner (internal/brain)
// carries exactly one judge field for both — NewConsolidateService's own
// existing shape (PR 9b added it for connect, PR 10b reused the same
// field for derive rather than widening the constructor a second time).
// When the two tasks name different providers, belief_derivation's client
// wins simply because it is resolved second in tasksConsolidateConsumes'
// own order — a disclosed gap neither spec.md nor design.md decides,
// carried here rather than silently picked without comment; binding both
// tasks to the same provider (the ordinary case) makes the order moot.
func resolveConsolidateProviders(cfg *config.Config, lookup func(string) (string, bool)) (judge ports.LLMProvider, embed ports.EmbeddingProvider, embedModel string, err error) {
	for _, task := range tasksConsolidateConsumes {
		binding, bound := cfg.Tasks[task]
		if !bound {
			return nil, nil, "", fmt.Errorf("consolidate: task %q has no provider bound — add it under tasks: in nooma.yml before running a pass", task)
		}
		provider, present := cfg.Providers[binding.Provider]
		if !present {
			return nil, nil, "", fmt.Errorf("consolidate: task %q names provider %q, which is not present in the providers map", task, binding.Provider)
		}
		client, buildErr := buildProvider(provider, lookup)
		if buildErr != nil {
			return nil, nil, "", fmt.Errorf("consolidate: task %q: %w", task, buildErr)
		}

		switch task {
		case "relation_evaluation", "belief_derivation":
			p, isLLM := client.(ports.LLMProvider)
			if !isLLM {
				return nil, nil, "", fmt.Errorf("consolidate: task %q is bound to a provider that cannot answer completions", task)
			}
			judge = p
		case "embedding":
			p, isEmbed := client.(ports.EmbeddingProvider)
			if !isEmbed {
				return nil, nil, "", fmt.Errorf("consolidate: task %q is bound to a provider that cannot embed", task)
			}
			embed = p
			embedModel = provider.Model
		}
	}
	return judge, embed, embedModel, nil
}

// wireConsolidate builds the real ConsolidateService over db and cfg —
// wireBrain's own shape (config -> providers -> repos -> RecallService ->
// service), but refusing with a named error instead of wireBrain's own
// (nil, nil) degrade: design §7.2's own MUST NOT — a pass that silently
// skipped connect/derive because a provider was unbound must never still
// write consolidation_last_run_at as though a full pass had run.
func wireConsolidate(ctx context.Context, db *sqlite.Vault, cfg *config.Config, lookup func(string) (string, bool)) (*brain.ConsolidateService, error) {
	judge, embed, embedModel, err := resolveConsolidateProviders(cfg, lookup)
	if err != nil {
		return nil, err
	}

	units := sqlite.NewUnitRepo(db)
	rels := sqlite.NewRelationRepo(db)
	lex := sqlite.NewSearch(db)
	embeds := sqlite.NewEmbeddingRepo(db)
	log := sqlite.NewDecisionLog(db)
	cfgRepo := sqlite.NewConfigRepo(db)
	selfModel := sqlite.NewSelfModelRepo(db)
	state := sqlite.NewStateRepo(db)

	loaded, err := embeds.LoadIndex(ctx, embedModel)
	if err != nil {
		return nil, fmt.Errorf("loading the resident vector index: %w", err)
	}
	index := brain.NewIndex(loaded)
	recall := brain.NewRecallService(index, lex, units, embed)

	return brain.NewConsolidateService(systemClock{}, cfgRepo, units, rels, uuidGen{}, log, recall, judge, selfModel, state), nil
}

// wireChannel builds the configured channel, or nothing.
//
// It returns (nil, nil) when Telegram is disabled, so a caller need not
// branch on configuration to find out whether there is a channel — the
// zero case is a nil Channel, not an error and not a channel that polls
// nothing.
//
// **Nothing calls this yet, deliberately.** Starting a poller in this
// change would mean every later PR runs against a live channel that has
// nothing to deliver — there is no delivery path until m3d, which wires it
// into runServe alongside the proactive_check tick. wiring_test.go asserts
// runServe does not reference it, so the absence is checked rather than
// remembered. ports.StateRepo was declared ahead of its own consumer the
// same way.
func wireChannel(cfg *config.Config, lookup func(string) (string, bool), log io.Writer) (ports.Channel, error) {
	if !cfg.Channels.Telegram.Enabled {
		return nil, nil
	}
	return telegram.New(cfg.Channels.Telegram, lookup, nil, "", log)
}

// wireCheck builds a *brain.CheckService over db. It resolves no provider
// and loads no index, because a due scan calls no model and searches
// nothing — the shortest wiring function in this file, and short for a
// reason worth stating rather than for one worth wondering about.
func wireCheck(db *sqlite.Vault) *brain.CheckService {
	return brain.NewCheckService(
		systemClock{},
		sqlite.NewTriggerRepo(db),
		sqlite.NewTimerRepo(db),
		uuidGen{},
		sqlite.NewDecisionLog(db),
		// No channel: `nooma check` is a one-shot subcommand that reports
		// what it did on stdout. Delivering through a channel is the
		// serve-time pass's job, and a subcommand that messaged the user
		// as a side effect of being run manually would be a surprise.
		nil,
		sqlite.NewUnitRepo(db),
		sqlite.NewStateRepo(db),
		// No provider either: a subcommand that spent an LLM call to
		// reword a timer nobody is listening to would be paying for a
		// sentence with no reader. The delivered text falls back to the
		// user's own words, which is what the rephrasing degrades to
		// anyway.
		nil,
		// No conversation, for the same reason as the nil channel above:
		// there is nowhere for this subcommand to push to.
		"",
	)
}

func wireBrain(ctx context.Context, db *sqlite.Vault, cfg *config.Config, lookup func(string) (string, bool)) (*brain.CaptureService, *brain.RecallService, error) {
	llm, judge, embed, embedModel, ok := resolveTaskProviders(cfg, lookup)
	if !ok {
		return nil, nil, nil
	}

	units := sqlite.NewUnitRepo(db)
	embeds := sqlite.NewEmbeddingRepo(db)
	lex := sqlite.NewSearch(db)
	rels := sqlite.NewRelationRepo(db)
	log := sqlite.NewDecisionLog(db)
	signals := sqlite.NewSignalRepo(db)
	triggers := sqlite.NewTriggerRepo(db)
	timers := sqlite.NewTimerRepo(db)

	loaded, err := embeds.LoadIndex(ctx, embedModel)
	if err != nil {
		return nil, nil, fmt.Errorf("loading the resident vector index: %w", err)
	}
	index := brain.NewIndex(loaded)

	capture := brain.NewCaptureService(systemClock{}, uuidGen{}, units, embeds, lex, rels, log, llm, judge, embed, index, signals, triggers, timers)
	recall := brain.NewRecallService(index, lex, units, embed)
	return capture, recall, nil
}

// wireScheduler builds the real *scheduler.Scheduler over db and cfg,
// reusing the *sqlite.Vault runServe already opened under its own lock
// (serve.go:71-89): no second vaultlock.Acquire anywhere, so the scheduler
// never fights nooma consolidate over two separate lock handles (spec
// R3.1).
//
// It mirrors wireBrain's own degrade-to-nil precedent (:236-238), not
// wireConsolidate's named-refusal one: a vault whose
// resolveConsolidateProviders refuses (an unbound task, an unconfigured
// provider name, a provider that cannot answer the task it is bound to —
// the same class of gap nooma consolidate's own CLI path already refuses
// on) yields a nil scheduler, a nil error, and one line on log naming why
// — not a failed runServe. HTTP capture and recall stay available on such
// a vault exactly as they do today (spec R3.2). resolveConsolidateProviders
// is checked here, ahead of wireConsolidate's own heavier call (which
// opens the resident vector index), the same two-step shape
// resolveTaskProviders/wireBrain already takes for capture/recall — a
// genuine failure past this point (the index failing to load) is not a
// configuration gap and still fails runServe outright.
//
// log is the scheduler's process log (scheduler.Deps.Log) — serve passes
// its errOut, per that field's own doc comment.
// proactiveCheck adapts brain.CheckService to scheduler.ProactiveChecker.
//
// The scheduler asks for one method and gets one; it holds no
// brain.CheckRequest and cannot ask for a dry run. A scheduled pass that
// could be a preview would be a pass that silently did nothing on a
// misconfigured vault.
type proactiveCheck struct{ svc *brain.CheckService }

func (p proactiveCheck) ProactiveCheck(ctx context.Context) error {
	_, err := p.svc.Check(ctx, brain.CheckRequest{})
	return err
}

// wireProactive builds the delivery pass the scheduler ticks.
//
// Unlike wireCheck, this one gets the channel: a scheduled pass is
// precisely the thing that should speak, where `nooma check` is a
// subcommand a person ran to look.
func wireProactive(db *sqlite.Vault, cfg *config.Config, lookup func(string) (string, bool), channel ports.Channel) (*brain.CheckService, error) {
	llm, _, _, err := resolveConsolidateProviders(cfg, lookup)
	if err != nil {
		// No provider bound. The pass still runs: a timer delivers the
		// user's own words, which is what the rephrasing degrades to
		// anyway (R4.1), and every other decision is pure.
		llm = nil
	}

	return brain.NewCheckService(
		systemClock{},
		sqlite.NewTriggerRepo(db),
		sqlite.NewTimerRepo(db),
		uuidGen{},
		sqlite.NewDecisionLog(db),
		channel,
		sqlite.NewUnitRepo(db),
		sqlite.NewStateRepo(db),
		llm,
		// The vault's one push destination, or none. Empty whenever the
		// config cannot name exactly one conversation — see
		// brain.ProactiveConversation for why it refuses to pick.
		brain.ProactiveConversation(cfg.Channels.Telegram.AllowedChatIDs),
	), nil
}

func wireScheduler(ctx context.Context, db *sqlite.Vault, cfg *config.Config, lookup func(string) (string, bool), log io.Writer, channel ports.Channel) (*scheduler.Scheduler, error) {
	if _, _, _, err := resolveConsolidateProviders(cfg, lookup); err != nil {
		_, _ = fmt.Fprintf(log, "scheduler: consolidation not scheduled: %v\n", err)
		return nil, nil
	}

	consolidate, err := wireConsolidate(ctx, db, cfg, lookup)
	if err != nil {
		return nil, fmt.Errorf("wiring the scheduler: %w", err)
	}

	check, err := wireProactive(db, cfg, lookup, channel)
	if err != nil {
		return nil, fmt.Errorf("wiring the proactive pass: %w", err)
	}

	sched, err := scheduler.New(scheduler.Deps{
		Clock:       systemClock{},
		Config:      sqlite.NewConfigRepo(db),
		Consolidate: consolidate,
		Proactive:   proactiveCheck{svc: check},
		Log:         log,
	})
	if err != nil {
		return nil, fmt.Errorf("wiring the scheduler: %w", err)
	}
	return sched, nil
}
