package main

import (
	"context"
	"crypto/rand"
	"fmt"
	"net/http"
	"time"

	"github.com/rengo/nooma/internal/brain"
	"github.com/rengo/nooma/internal/config"
	"github.com/rengo/nooma/internal/ports"
	"github.com/rengo/nooma/internal/providers/anthropic"
	"github.com/rengo/nooma/internal/providers/ollama"
	"github.com/rengo/nooma/internal/providers/openai"
	"github.com/rengo/nooma/internal/store/sqlite"
)

// systemClock is the production ports.Clock — the one place in this binary
// that calls time.Now (nooma-core: internal/core and internal/brain never
// do; docs/06-harness.md §2). It hands CaptureService.Capture's own single
// read (design D4) a real instant; nothing else in this command reads the
// clock.
type systemClock struct{}

func (systemClock) Now() time.Time { return time.Now() }

// uuidGen is the production ports.IDGen: a version-4 UUID
// (docs/03-data-model.md: "TEXT UUID v4 generated by the application"),
// built over crypto/rand rather than a new module dependency for sixteen
// random bytes and two bit-level fixups.
type uuidGen struct{}

func (uuidGen) New() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		// The OS's entropy source failing is not a condition this binary
		// can degrade under — every id it would generate from here on is
		// unusable, the same posture serve already takes toward a broken
		// environment elsewhere in this command.
		panic(fmt.Sprintf("uuidGen: reading random bytes: %v", err))
	}
	b[6] = (b[6] & 0x0f) | 0x40 // version 4
	b[8] = (b[8] & 0x3f) | 0x80 // variant 10
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

// buildProvider constructs the client cfg.Providers[name] describes. lookup
// resolves an api_key_env name to its value, the same injected-environment
// shape every other config-adjacent call in this command already takes.
//
// It returns the client as `any` on purpose: which port(s) the result
// satisfies is not this function's decision. Only ollama.Client implements
// both ports.LLMProvider and ports.EmbeddingProvider today — anthropic.Client
// and openai.Client implement just the first, until 17 gives openai.Client
// an Embed method — so resolveTaskProviders below asserts the port each
// task actually needs at its own call site, rather than this function
// promising one it cannot always keep.
func buildProvider(p config.Provider, lookup func(string) (string, bool)) (any, error) {
	switch p.Type {
	case "anthropic":
		apiKey, _ := lookup(p.APIKeyEnv)
		return anthropic.NewClient(p.Endpoint, apiKey, p.Model, http.DefaultClient), nil
	case "openai":
		apiKey, _ := lookup(p.APIKeyEnv)
		return openai.NewClient(p.Endpoint, apiKey, p.Model, http.DefaultClient), nil
	case "ollama":
		return ollama.NewClient(p.Endpoint, p.Model, http.DefaultClient), nil
	default:
		return nil, fmt.Errorf("provider type %q has no client this binary wires (whisper_cpp is audio-only)", p.Type)
	}
}

// resolveTaskProviders resolves every task tasksM1Consumes names (design
// D18a) against cfg.Tasks and cfg.Providers, asserting each one to the port
// it actually needs. It reads tasksM1Consumes itself, not a restated copy —
// TestResolveTaskProvidersReadsTheSharedListNotACopy (tasks_test.go) proves
// it by swapping the package var and observing this function's own
// resolution follow it.
//
// ok is false whenever ANY of the three is unresolved: an unbound task, a
// task bound to a provider name absent from cfg.Providers (unreachable once
// Validate has run, checked again here defensively), a provider type this
// binary has no client for, or a provider whose type does not implement the
// port that task needs — an anthropic- or openai-typed embedding binding,
// until 17 lands. This is deliberately all-or-nothing, not a per-task
// degradation: RecallService.ScoredFor dereferences its own embed field
// unconditionally (unlike Candidates, it has no nil guard on a missing
// vector), so handing NewCaptureService/NewRecallService a nil
// ports.EmbeddingProvider is not a degraded leg — it is a nil-interface
// panic on the first capture or recall. Falling back to the honest 503 the
// existing nil-Deps guards (13b, 13c) already answer with is what "safe
// defaults are structural" (CLAUDE.md non-negotiable #7) means applied to a
// half-configured provider set, the same posture it already takes toward
// the auth token.
func resolveTaskProviders(cfg *config.Config, lookup func(string) (string, bool)) (llm, judge ports.LLMProvider, embed ports.EmbeddingProvider, embedModel string, ok bool) {
	for _, task := range tasksM1Consumes {
		binding, bound := cfg.Tasks[task]
		if !bound {
			return nil, nil, nil, "", false
		}
		provider, present := cfg.Providers[binding.Provider]
		if !present {
			return nil, nil, nil, "", false
		}
		client, err := buildProvider(provider, lookup)
		if err != nil {
			return nil, nil, nil, "", false
		}

		switch task {
		case "capture_processing":
			p, isLLM := client.(ports.LLMProvider)
			if !isLLM {
				return nil, nil, nil, "", false
			}
			llm = p
		case "relation_evaluation":
			p, isLLM := client.(ports.LLMProvider)
			if !isLLM {
				return nil, nil, nil, "", false
			}
			judge = p
		case "embedding":
			p, isEmbed := client.(ports.EmbeddingProvider)
			if !isEmbed {
				return nil, nil, nil, "", false
			}
			embed = p
			embedModel = provider.Model
		}
	}
	return llm, judge, embed, embedModel, true
}

// wireBrain builds the real CaptureService/RecallService pair over db and
// cfg — design D10's own "config -> providers -> repos -> Index -> services"
// chain, resolved once at vault open (ADR-0012), not per request.
//
// It returns nil, nil (no error) whenever resolveTaskProviders could not
// resolve every task tasksM1Consumes names: that is not a startup failure,
// it is the same transitional state cmd/nooma/serve.go was already in
// before this PR, now reachable by a genuine configuration gap (a fresh
// vault with no providers bound yet) rather than only by "13d has not
// landed." The caller passes the result straight into
// httpapi.Handler(Deps{Capture, Recall}), whose existing nil guards (13b,
// 13c) answer it honestly over HTTP instead of this command refusing to
// serve at all.
func wireBrain(ctx context.Context, db *sqlite.Vault, cfg *config.Config, lookup func(string) (string, bool)) (*brain.CaptureService, *brain.RecallService, error) {
	llm, judge, embed, embedModel, ok := resolveTaskProviders(cfg, lookup)
	if !ok {
		return nil, nil, nil
	}

	units := sqlite.NewUnitRepo(db)
	embeds := sqlite.NewEmbeddingRepo(db)
	lex := sqlite.NewSearch(db)
	rels := sqlite.NewRelationRepo(db)
	log := sqlite.NewDecisionLog(db)
	signals := sqlite.NewSignalRepo(db)

	loaded, err := embeds.LoadIndex(ctx, embedModel)
	if err != nil {
		return nil, nil, fmt.Errorf("loading the resident vector index: %w", err)
	}
	index := brain.NewIndex(loaded)

	capture := brain.NewCaptureService(systemClock{}, uuidGen{}, units, embeds, lex, rels, log, llm, judge, embed, index, signals)
	recall := brain.NewRecallService(index, lex, units, embed)
	return capture, recall, nil
}
