package schema

import (
	"reflect"
	"testing"
)

// TestMarshalOrdersObjectsAndColumns asserts design §6.2's sort: objects by
// (kind rank, name) with rank table < virtual_table < index < unique_index
// < trigger < view, and each object's columns by name — independent of the
// order they were appended in.
func TestMarshalOrdersObjectsAndColumns(t *testing.T) {
	objs := []Object{
		{Kind: KindTrigger, Name: "units_fts_au"},
		{Kind: KindTable, Name: "units", Columns: []string{"content", "id"}},
		{Kind: KindUniqueIndex, Name: "idx_units_unique_active_insight"},
		{Kind: KindTable, Name: "relations", Columns: []string{"to_unit_id", "from_unit_id"}},
		{Kind: KindIndex, Name: "idx_units_status_touched"},
	}

	got := Marshal(objs, 1)
	want := "" +
		"# nooma schema structure golden — generated by `make schema-golden`, do not edit.\n" +
		"# Compared against docs/03-data-model.md by TestHarness_SchemaMatchesDoc03 (L2).\n" +
		"schema_version 1\n\n" +
		"table relations\n" +
		"  column from_unit_id\n" +
		"  column to_unit_id\n" +
		"table units\n" +
		"  column content\n" +
		"  column id\n" +
		"index idx_units_status_touched\n" +
		"unique_index idx_units_unique_active_insight\n" +
		"trigger units_fts_au\n"

	if string(got) != want {
		t.Errorf("Marshal(...) =\n%s\nwant\n%s", got, want)
	}
}

// TestParseGoldenRoundTrips asserts ParseGolden recovers the same objects
// Marshal produced (D10-adjacent guard: the golden format must be its own
// inverse, or a future regeneration could silently drift from what
// TestHarness_SchemaMatchesDoc03 (PR 4) actually compares against).
func TestParseGoldenRoundTrips(t *testing.T) {
	objs := []Object{
		{Kind: KindTable, Name: "units", Columns: []string{"content", "id"}},
		{Kind: KindVirtualTable, Name: "units_fts", Columns: []string{"content"}},
		{Kind: KindIndex, Name: "idx_units_status_touched"},
		{Kind: KindUniqueIndex, Name: "idx_units_unique_active_insight"},
		{Kind: KindTrigger, Name: "units_fts_ai"},
	}

	golden := Marshal(objs, 2)

	got, err := ParseGolden(golden)
	if err != nil {
		t.Fatalf("ParseGolden(...) = _, %v, want nil error", err)
	}

	want := make([]Object, len(objs))
	copy(want, objs)
	Sort(want)

	if !reflect.DeepEqual(got, want) {
		t.Errorf("ParseGolden(Marshal(objs)) = %#v, want %#v", got, want)
	}
}

// TestParseGoldenSkipsCommentsAndBlankLines proves the parser ignores the
// header comments and the schema_version line, which are not schema
// content.
func TestParseGoldenSkipsCommentsAndBlankLines(t *testing.T) {
	golden := []byte("# a comment\nschema_version 2\n\ntable units\n  column id\nindex idx_x\n")

	got, err := ParseGolden(golden)
	if err != nil {
		t.Fatalf("ParseGolden(...) = _, %v, want nil error", err)
	}
	want := []Object{
		{Kind: KindTable, Name: "units", Columns: []string{"id"}},
		{Kind: KindIndex, Name: "idx_x"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("ParseGolden(...) = %#v, want %#v", got, want)
	}
}
