// Package schema holds the stdlib-only structural projection of the
// database schema (design D1/§6.4, openspec/changes/complete-harness):
// Kind and Object describe one object's shape, Marshal/ParseGolden
// serialize and read back testdata/schema/structure.golden. ParseMarkdown
// and Diff — the docs/03-data-model.md side of the comparison — land in a
// later PR of this same change, once the doc-03 gate needs them.
//
// This package deliberately imports nothing beyond the standard library
// (design §3): FromSQLite, which needs database/sql, stays in the L3 test
// file that generates the golden, not here.
package schema

import (
	"bufio"
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// Kind names the category of a schema object, read from the normalized DDL
// prefix rather than sqlite_master.type alone (design §6.2): a virtual
// table and a unique index need their own Kind so the golden's sort and a
// future doc-03 comparison can tell them apart from an ordinary table or
// index.
type Kind string

const (
	KindTable        Kind = "table"
	KindVirtualTable Kind = "virtual_table"
	KindIndex        Kind = "index"
	KindUniqueIndex  Kind = "unique_index"
	KindTrigger      Kind = "trigger"
	KindView         Kind = "view"
)

// kindRank orders Kind values for the structural golden's sort (design
// §6.2): table < virtual_table < index < unique_index < trigger < view.
var kindRank = map[Kind]int{
	KindTable:        0,
	KindVirtualTable: 1,
	KindIndex:        2,
	KindUniqueIndex:  3,
	KindTrigger:      4,
	KindView:         5,
}

// Object is one schema object's structural projection: its kind, name,
// and, for a table or virtual table, its column name set. Types, NOT
// NULL, defaults, FK clauses, trigger bodies and index predicates are
// deliberately not part of this projection — ddl.golden carries those
// instead (design §6.2/§6.3).
type Object struct {
	Kind    Kind
	Name    string
	Columns []string
}

// Sort orders objs by (kind rank, name) and each object's Columns by name
// (design §6.2), in place.
func Sort(objs []Object) {
	sort.Slice(objs, func(i, j int) bool {
		if objs[i].Kind != objs[j].Kind {
			return kindRank[objs[i].Kind] < kindRank[objs[j].Kind]
		}
		return objs[i].Name < objs[j].Name
	})
	for i := range objs {
		sort.Strings(objs[i].Columns)
	}
}

// Marshal renders objs as testdata/schema/structure.golden's format
// (design §6.2): a two-space-indent, one-object-or-column-per-line text
// file with schemaVersion (the highest published migration version, R3.8)
// recorded as a header line. objs is not mutated; Marshal sorts a copy.
func Marshal(objs []Object, schemaVersion int) []byte {
	sorted := make([]Object, len(objs))
	copy(sorted, objs)
	Sort(sorted)

	var b strings.Builder
	b.WriteString("# nooma schema structure golden — generated by `make schema-golden`, do not edit.\n")
	b.WriteString("# Compared against docs/03-data-model.md by TestHarness_SchemaMatchesDoc03 (L2).\n")
	fmt.Fprintf(&b, "schema_version %d\n\n", schemaVersion)

	for _, obj := range sorted {
		fmt.Fprintf(&b, "%s %s\n", obj.Kind, obj.Name)
		for _, col := range obj.Columns {
			fmt.Fprintf(&b, "  column %s\n", col)
		}
	}

	return []byte(b.String())
}

// ParseGolden parses testdata/schema/structure.golden's format back into
// Objects, sorted the same way Marshal would sort them. Comment lines
// (#...) and the schema_version header are recognized and skipped — they
// are not schema content.
func ParseGolden(b []byte) ([]Object, error) {
	var objs []Object
	var current *Object

	scanner := bufio.NewScanner(bytes.NewReader(b))
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)

		switch {
		case trimmed == "" || strings.HasPrefix(trimmed, "#") || strings.HasPrefix(trimmed, "schema_version "):
			continue
		case strings.HasPrefix(line, "  column "):
			if current == nil {
				return nil, fmt.Errorf("column line %q precedes any object", line)
			}
			current.Columns = append(current.Columns, strings.TrimPrefix(line, "  column "))
		default:
			if current != nil {
				objs = append(objs, *current)
			}
			kind, name, ok := strings.Cut(trimmed, " ")
			if !ok {
				return nil, fmt.Errorf("malformed object line: %q", line)
			}
			current = &Object{Kind: Kind(kind), Name: name}
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan golden: %w", err)
	}
	if current != nil {
		objs = append(objs, *current)
	}

	Sort(objs)
	return objs, nil
}
