//go:build integration

package integration

import (
	"bufio"
	"os"
	"strings"
	"testing"
)

// TestSchemaGoldenAnchorsExpectedObjects is the four-lens pre-PR review's
// CRITICAL finding 3: a golden regenerated by the code under test cannot
// catch a bug in the generator itself. `TestSchemaGolden` (schema_golden_test.go)
// dumps sqlite_master through dumpSchema, which calls schema.Classify and
// schema.IsShadowTable, then compares that dump against the committed
// golden files — but those same files are what `make schema-golden`
// (dumpSchema, -update) regenerates. A bug in dumpSchema's own
// classification/exclusion logic silently regenerates a golden that agrees
// with itself and the gate stays green — this is not hypothetical: reverting
// the `r.Kind == schema.KindTable` guard in dumpSchema and running `make
// schema-golden` drops all three FTS5 sync triggers from structure.golden
// with zero test failure anywhere.
//
// This test is the anchor outside the generator: an explicit, hand-written
// list of objects that MUST appear in structure.golden, checked by exact
// line match against the golden file's own committed bytes — it never calls
// dumpSchema, schema.Classify, or schema.IsShadowTable, so no bug in any of
// those three can make this test silently agree with a bad regeneration.
// Regenerating the golden cannot silence it, because the expectation here
// is hand-written, not generated.
//
// RED, watched (verbatim): temporarily changed dumpSchema's exclusion guard
// from
//
//	if r.Kind == schema.KindTable && schema.IsShadowTable(r.Name, virtualTables) {
//
// to
//
//	if schema.IsShadowTable(r.Name, virtualTables) {
//
// (dropping the Kind gate — exactly the pre-fix shape the slice-4a review
// found), then ran `go test -tags integration ./test/integration/ -run
// TestSchemaGolden -update` to regenerate structure.golden from that
// mutated generator:
//
//	--- FAIL: TestSchemaGoldenAnchorsExpectedObjects (0.00s)
//	    schema_golden_anchor_test.go: structure.golden is missing required line "trigger units_fts_ai" — the golden's own generator dropped it (see schema_golden_test.go's dumpSchema Kind guard)
//	    schema_golden_anchor_test.go: structure.golden is missing required line "trigger units_fts_ad" — the golden's own generator dropped it (see schema_golden_test.go's dumpSchema Kind guard)
//	    schema_golden_anchor_test.go: structure.golden is missing required line "trigger units_fts_au" — the golden's own generator dropped it (see schema_golden_test.go's dumpSchema Kind guard)
//
// Meanwhile `TestSchemaGolden` itself PASSED against that same regenerated
// (self-consistent, self-blind) golden — precisely the failure mode this
// test exists to close. Restoring the Kind guard and regenerating make both
// tests pass again.
func TestSchemaGoldenAnchorsExpectedObjects(t *testing.T) {
	golden, err := os.ReadFile(structureGoldenPath)
	if err != nil {
		t.Fatalf("os.ReadFile(%q) = _, %v, want nil error", structureGoldenPath, err)
	}

	// objectLines holds only the object-declaration lines (one per schema
	// object: "table foo", "trigger bar", ...) — column lines ("  column
	// ..."), the header comments and the schema_version line are not
	// objects and must not be compared against the required list below.
	objectLines := make(map[string]bool)
	scanner := bufio.NewScanner(strings.NewReader(string(golden)))
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		switch {
		case trimmed == "":
		case strings.HasPrefix(trimmed, "#"):
		case strings.HasPrefix(trimmed, "schema_version "):
		case strings.HasPrefix(line, "  column "):
		default:
			objectLines[trimmed] = true
		}
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan %q: %v", structureGoldenPath, err)
	}

	// When you add a CREATE statement to a migration that changes this
	// golden, add its object line here too — exact set equality (both
	// directions) below means an object added to the golden without a
	// matching update here fails this test instead of silently passing.
	required := []string{
		// 0001_core_tables.sql
		"table units",
		"index idx_units_status_touched",
		"unique_index idx_units_unique_active_insight",
		"table relations",
		"table triggers",
		"index idx_triggers_status_fire",
		"table timers",
		"table self_beliefs",
		"table current_state",
		"table decision_log",
		"index idx_decision_log_occurred",
		// 0002_learning_and_search.sql
		"table learning_signals",
		"index idx_learning_signals_occurred",
		"table learning_state",
		"table relation_thresholds",
		"table calibration",
		"table measurements",
		"index idx_measurements_metric",
		"index idx_measurements_ref_unit",
		"table config",
		"table unit_embeddings",
		"index idx_unit_embeddings_model",
		"virtual_table units_fts",
		// The three FTS5 sync triggers (R9.1) — the exact objects the
		// slice-4a review found silently dropped by an unguarded
		// IsShadowTable call.
		"trigger units_fts_ai",
		"trigger units_fts_ad",
		"trigger units_fts_au",
	}

	requiredSet := make(map[string]bool, len(required))
	for _, want := range required {
		requiredSet[want] = true
		if !objectLines[want] {
			t.Errorf("%s is missing required line %q — the golden's own generator dropped it (see schema_golden_test.go's dumpSchema Kind guard)", structureGoldenPath, want)
		}
	}

	// The direction slice-4a's version of this test did not check: an
	// object PRESENT in the golden but ABSENT from this hand-written list.
	// Membership alone would silently pass if an object were added to the
	// golden without updating required above — exactly the gap
	// TestSchemaDocAnchorsExpectedObjectCount (slice 4b,
	// test/conformance/schema_doc_test.go) closed on the doc-03 side (four-
	// lens pre-PR review finding 6: bring 4a's anchor up to the same
	// standard).
	for got := range objectLines {
		if !requiredSet[got] {
			t.Errorf("%s declares object %q which is not in this test's hand-written required list — add it here (or confirm the addition is intentional)", structureGoldenPath, got)
		}
	}
	if len(objectLines) != len(required) {
		t.Errorf("%s declares %d objects, but this test's hand-written required list has %d — update the list to match", structureGoldenPath, len(objectLines), len(required))
	}
}
