//go:build integration

package integration

import (
	"bufio"
	"os"
	"strings"
	"testing"
)

// TestSchemaGoldenAnchorsExpectedObjects is the four-lens pre-PR review's
// CRITICAL finding 3: a golden regenerated by the code under test cannot
// catch a bug in the generator itself. `TestSchemaGolden` (schema_golden_test.go)
// dumps sqlite_master through dumpSchema, which calls schema.Classify and
// schema.IsShadowTable, then compares that dump against the committed
// golden files — but those same files are what `make schema-golden`
// (dumpSchema, -update) regenerates. A bug in dumpSchema's own
// classification/exclusion logic silently regenerates a golden that agrees
// with itself and the gate stays green — this is not hypothetical: reverting
// the `r.Kind == schema.KindTable` guard in dumpSchema and running `make
// schema-golden` drops all three FTS5 sync triggers from structure.golden
// with zero test failure anywhere.
//
// This test is the anchor outside the generator: an explicit, hand-written
// list of objects that MUST appear in structure.golden, checked by exact
// line match against the golden file's own committed bytes — it never calls
// dumpSchema, schema.Classify, or schema.IsShadowTable, so no bug in any of
// those three can make this test silently agree with a bad regeneration.
// Regenerating the golden cannot silence it, because the expectation here
// is hand-written, not generated.
//
// RED, watched (verbatim): temporarily changed dumpSchema's exclusion guard
// from
//
//	if r.Kind == schema.KindTable && schema.IsShadowTable(r.Name, virtualTables) {
//
// to
//
//	if schema.IsShadowTable(r.Name, virtualTables) {
//
// (dropping the Kind gate — exactly the pre-fix shape the slice-4a review
// found), then ran `go test -tags integration ./test/integration/ -run
// TestSchemaGolden -update` to regenerate structure.golden from that
// mutated generator:
//
//	--- FAIL: TestSchemaGoldenAnchorsExpectedObjects (0.00s)
//	    schema_golden_anchor_test.go: structure.golden is missing required line "trigger units_fts_ai" — the golden's own generator dropped it (see schema_golden_test.go's dumpSchema Kind guard)
//	    schema_golden_anchor_test.go: structure.golden is missing required line "trigger units_fts_ad" — the golden's own generator dropped it (see schema_golden_test.go's dumpSchema Kind guard)
//	    schema_golden_anchor_test.go: structure.golden is missing required line "trigger units_fts_au" — the golden's own generator dropped it (see schema_golden_test.go's dumpSchema Kind guard)
//
// Meanwhile `TestSchemaGolden` itself PASSED against that same regenerated
// (self-consistent, self-blind) golden — precisely the failure mode this
// test exists to close. Restoring the Kind guard and regenerating make both
// tests pass again.
func TestSchemaGoldenAnchorsExpectedObjects(t *testing.T) {
	golden, err := os.ReadFile(structureGoldenPath)
	if err != nil {
		t.Fatalf("os.ReadFile(%q) = _, %v, want nil error", structureGoldenPath, err)
	}

	lines := make(map[string]bool)
	scanner := bufio.NewScanner(strings.NewReader(string(golden)))
	for scanner.Scan() {
		lines[strings.TrimSpace(scanner.Text())] = true
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan %q: %v", structureGoldenPath, err)
	}

	// Hand-written, not generated: every table 0001_core_tables.sql and
	// 0002_learning_and_search.sql create, the virtual table, and — the
	// whole point of this test — the three FTS5 sync triggers R9.1
	// requires. Kept as one flat list (not derived from schema.Kind
	// constants) so nothing here shares code with the thing being guarded
	// against.
	required := []string{
		// 0001_core_tables.sql
		"table units",
		"table relations",
		"table triggers",
		"table timers",
		"table self_beliefs",
		"table current_state",
		"table decision_log",
		// 0002_learning_and_search.sql
		"table learning_signals",
		"table learning_state",
		"table relation_thresholds",
		"table calibration",
		"table measurements",
		"table config",
		"table unit_embeddings",
		"virtual_table units_fts",
		// The three FTS5 sync triggers (R9.1) — the exact objects the
		// slice-4a review found silently dropped by an unguarded
		// IsShadowTable call.
		"trigger units_fts_ai",
		"trigger units_fts_ad",
		"trigger units_fts_au",
	}

	for _, want := range required {
		if !lines[want] {
			t.Errorf("%s is missing required line %q — the golden's own generator dropped it (see schema_golden_test.go's dumpSchema Kind guard)", structureGoldenPath, want)
		}
	}
}
